---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: foobar-api
  namespace: linkerd-examples
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-api
  namespace: linkerd-examples