---
apiVersion: v1
kind: Service
metadata: 
  name: foobar-api
  namespace: linkerd-examples
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector: 
    app: foobar-api
---
apiVersion: v1
kind: Service
metadata:
  name: web-api
  namespace: linkerd-examples
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: web-api
  type: ClusterIP